/**
 * Scaffold command - Generate standalone web app from schema and scad file
 * @license GPL-3.0-or-later
 */

import { readFileSync, writeFileSync, mkdirSync, cpSync, existsSync } from 'fs';
import { resolve, join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Get template directory path
 * @param {string} templateName - Template name (vanilla|react|vue|svelte)
 * @returns {string} Template directory path
 */
function getTemplateDir(templateName) {
  return join(__dirname, '..', 'templates', templateName);
}

/**
 * Copy directory recursively
 * @param {string} src - Source directory
 * @param {string} dest - Destination directory
 */
function copyDirectory(src, dest) {
  if (!existsSync(src)) {
    throw new Error(`Template directory not found: ${src}`);
  }
  mkdirSync(dest, { recursive: true });
  cpSync(src, dest, { recursive: true });
}

/**
 * Generate index.html with embedded schema and scad
 * @param {Object} schema - Parameter schema
 * @param {string} scadContent - OpenSCAD source code
 * @param {Object} options - Scaffold options
 * @returns {string} Generated HTML content
 */
function generateIndexHtml(schema, scadContent, options) {
  const title = options.title || schema.title || 'OpenSCAD Customizer';
  
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${schema.description || 'Customize and render OpenSCAD models'}" />
    <title>${title}</title>
    
    <!-- Preload critical resources -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    
    <!-- Theme -->
    <meta name="theme-color" content="#2563eb" />
    
    <!-- Embedded Schema -->
    <script type="application/json" id="param-schema">
${JSON.stringify(schema, null, 2)}
    </script>
    
    <!-- Embedded OpenSCAD Source -->
    <script type="text/plain" id="scad-source">
${scadContent}
    </script>
  </head>
  <body>
    <div id="app">
      <header>
        <h1>${title}</h1>
        <p>${schema.description || ''}</p>
      </header>
      
      <main class="container">
        <div class="layout">
          <aside class="params-panel">
            <div id="parameters-form"></div>
          </aside>
          
          <section class="preview-panel">
            <div id="preview-container"></div>
            <div class="actions">
              <button id="render-btn" class="primary">Generate STL</button>
              <button id="download-btn" class="secondary" disabled>Download STL</button>
            </div>
          </section>
        </div>
      </main>
      
      <footer>
        <p>Generated by OpenSCAD Forge • <a href="https://github.com/yourusername/openscad-web-customizer-forge">Source Code</a></p>
      </footer>
    </div>
    
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;
}

/**
 * Generate package.json for the scaffolded app
 * @param {Object} schema - Parameter schema
 * @param {Object} options - Scaffold options
 * @returns {Object} Package.json content
 */
function generatePackageJson(schema, options) {
  const appName = (options.title || schema.title || 'openscad-customizer')
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, '-');
  
  const baseDeps = {
    ajv: '^8.12.0',
    jszip: '^3.10.1',
    'openscad-wasm-prebuilt': '^1.2.0',
    three: '^0.160.0',
  };

  const baseDevDeps = {
    vite: '^5.0.0',
  };

  // Add template-specific dependencies
  if (options.template === 'react') {
    baseDeps.react = '^18.2.0';
    baseDeps['react-dom'] = '^18.2.0';
    baseDevDeps['@vitejs/plugin-react'] = '^4.2.1';
    baseDevDeps['@types/react'] = '^18.2.43';
    baseDevDeps['@types/react-dom'] = '^18.2.17';
  } else if (options.template === 'vue') {
    baseDeps.vue = '^3.4.0';
    baseDevDeps['@vitejs/plugin-vue'] = '^5.0.0';
  } else if (options.template === 'svelte') {
    baseDevDeps.svelte = '^4.2.0';
    baseDevDeps['@sveltejs/vite-plugin-svelte'] = '^3.0.0';
  } else if (options.template === 'angular') {
    baseDeps['@angular/core'] = '^17.0.0';
    baseDeps['@angular/common'] = '^17.0.0';
    baseDeps['@angular/platform-browser'] = '^17.0.0';
    baseDeps['@angular/forms'] = '^17.0.0';
    baseDeps['rxjs'] = '^7.8.0';
    baseDeps['zone.js'] = '^0.14.0';
    baseDevDeps['@analogjs/vite-plugin-angular'] = '^1.0.0';
    baseDevDeps['typescript'] = '^5.3.0';
  } else if (options.template === 'preact') {
    baseDeps.preact = '^10.19.0';
    baseDevDeps['@preact/preset-vite'] = '^2.8.0';
  }
  
  return {
    name: appName,
    version: '1.0.0',
    description: schema.description || 'OpenSCAD Customizer Web App',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'vite build',
      preview: 'vite preview',
    },
    dependencies: baseDeps,
    devDependencies: baseDevDeps,
  };
}

/**
 * Generate README.md for the scaffolded app
 * @param {Object} schema - Parameter schema
 * @param {Object} options - Scaffold options
 * @returns {string} README content
 */
function generateReadme(schema, options) {
  const title = options.title || schema.title || 'OpenSCAD Customizer';
  const description = schema.description || 'Customize and render OpenSCAD models in your browser';
  
  return `# ${title}

${description}

## Features

- 🎨 Interactive parameter customization
- 🔄 Real-time preview
- 📦 STL export for 3D printing
- 🌐 100% client-side rendering
- ♿ Accessibility-first design

## Getting Started

### Prerequisites

- Node.js 18+
- npm 9+

### Installation

\`\`\`bash
npm install
\`\`\`

### Development

\`\`\`bash
npm run dev
\`\`\`

Open http://localhost:5173 in your browser.

### Build for Production

\`\`\`bash
npm run build
\`\`\`

The built files will be in the \`dist/\` directory.

## Parameters

This customizer has ${Object.keys(schema.properties || {}).length} parameters${schema['x-groups'] ? ` organized in ${schema['x-groups'].length} groups` : ''}.

${generateParameterTable(schema)}

## License

${schema['x-metadata']?.license || 'GPL-3.0-or-later'}

## Generated by

[OpenSCAD Forge](https://github.com/yourusername/openscad-web-customizer-forge) - Developer toolchain for OpenSCAD Customizer projects
`;
}

/**
 * Generate parameter table for README
 * @param {Object} schema - Parameter schema
 * @returns {string} Markdown table
 */
function generateParameterTable(schema) {
  if (!schema.properties || Object.keys(schema.properties).length === 0) {
    return '_No parameters defined._';
  }
  
  let table = '| Parameter | Type | Default | Description |\n';
  table += '|-----------|------|---------|-------------|\n';
  
  for (const [name, prop] of Object.entries(schema.properties)) {
    const type = prop.type;
    const defaultVal = JSON.stringify(prop.default);
    const desc = prop.description || prop.title || '';
    table += `| ${name} | ${type} | ${defaultVal} | ${desc} |\n`;
  }
  
  return table;
}

/**
 * Scaffold command handler
 * @param {Object} options - Command options
 */
export async function scaffoldCommand(options) {
  try {
    console.log(chalk.blue('🏗️  OpenSCAD Forge - Project Scaffolding'));
    
    // Validate inputs
    const schemaPath = resolve(options.schema);
    const scadPath = resolve(options.scad);
    const outDir = resolve(options.out);
    
    console.log(chalk.gray(`Schema: ${schemaPath}`));
    console.log(chalk.gray(`OpenSCAD: ${scadPath}`));
    console.log(chalk.gray(`Output: ${outDir}`));
    console.log(chalk.gray(`Template: ${options.template}`));
    
    // Check if output directory exists
    if (existsSync(outDir)) {
      console.error(chalk.red(`✗ Output directory already exists: ${outDir}`));
      console.log(chalk.yellow('Hint: Choose a different output directory or remove the existing one'));
      process.exit(1);
    }
    
    // Read schema
    let schema;
    try {
      const schemaContent = readFileSync(schemaPath, 'utf-8');
      schema = JSON.parse(schemaContent);
    } catch (err) {
      console.error(chalk.red(`✗ Failed to read schema: ${err.message}`));
      process.exit(1);
    }
    
    // Read OpenSCAD file
    let scadContent;
    try {
      scadContent = readFileSync(scadPath, 'utf-8');
    } catch (err) {
      console.error(chalk.red(`✗ Failed to read OpenSCAD file: ${err.message}`));
      process.exit(1);
    }
    
    console.log(chalk.green('✓ Files validated'));
    
    // Get template directory
    const templateDir = getTemplateDir(options.template);
    
    // Determine source directory based on template
    let srcDir;
    if (options.template === 'vanilla') {
      srcDir = join(__dirname, '..', '..', 'src');
      if (!existsSync(srcDir)) {
        console.error(chalk.red(`✗ Source directory not found: ${srcDir}`));
        process.exit(1);
      }
    } else if (['react', 'vue', 'svelte', 'angular', 'preact'].includes(options.template)) {
      srcDir = join(__dirname, '..', 'templates', options.template, 'src');
      if (!existsSync(srcDir)) {
        console.error(chalk.red(`✗ ${options.template.charAt(0).toUpperCase() + options.template.slice(1)} template directory not found: ${srcDir}`));
        process.exit(1);
      }
    } else {
      console.error(chalk.red(`✗ Unknown template: ${options.template}`));
      console.log(chalk.yellow('Available templates: vanilla, react, vue, svelte, angular, preact'));
      process.exit(1);
    }
    
    console.log(chalk.gray('Copying template files...'));
    
    // Create output directory structure
    mkdirSync(outDir, { recursive: true });
    mkdirSync(join(outDir, 'src'), { recursive: true });
    mkdirSync(join(outDir, 'public'), { recursive: true });
    
    // Copy src directory
    try {
      cpSync(srcDir, join(outDir, 'src'), { recursive: true });
      console.log(chalk.green('✓ Copied source files'));
    } catch (err) {
      console.error(chalk.red(`✗ Failed to copy source files: ${err.message}`));
      process.exit(1);
    }
    
    // Copy public directory
    const publicDir = join(__dirname, '..', '..', 'public');
    if (existsSync(publicDir)) {
      try {
        cpSync(publicDir, join(outDir, 'public'), { recursive: true });
        console.log(chalk.green('✓ Copied public assets'));
      } catch (err) {
        console.error(chalk.red(`✗ Failed to copy public assets: ${err.message}`));
        process.exit(1);
      }
    }
    
    // Generate index.html
    if (['react', 'vue', 'svelte', 'angular', 'preact'].includes(options.template)) {
      // Use framework template
      const templatePath = join(__dirname, '..', 'templates', options.template, 'index.html.template');
      let indexTemplate = readFileSync(templatePath, 'utf-8');
      indexTemplate = indexTemplate.replace('{{TITLE}}', options.title || schema.title || 'OpenSCAD Customizer');
      indexTemplate = indexTemplate.replace('{{DESCRIPTION}}', schema.description || 'Customize and render OpenSCAD models');
      indexTemplate = indexTemplate.replace('{{SCHEMA}}', JSON.stringify(schema, null, 2));
      indexTemplate = indexTemplate.replace('{{SCAD_SOURCE}}', scadContent);
      writeFileSync(join(outDir, 'index.html'), indexTemplate, 'utf-8');
    } else {
      // Use vanilla template
      const indexHtml = generateIndexHtml(schema, scadContent, options);
      writeFileSync(join(outDir, 'index.html'), indexHtml, 'utf-8');
    }
    console.log(chalk.green('✓ Generated index.html'));
    
    // Generate package.json
    const packageJson = generatePackageJson(schema, options);
    writeFileSync(join(outDir, 'package.json'), JSON.stringify(packageJson, null, 2) + '\n', 'utf-8');
    console.log(chalk.green('✓ Generated package.json'));
    
    // Generate README.md
    const readme = generateReadme(schema, options);
    writeFileSync(join(outDir, 'README.md'), readme, 'utf-8');
    console.log(chalk.green('✓ Generated README.md'));
    
    // Copy or generate vite.config.js
    if (['react', 'vue', 'svelte', 'angular', 'preact'].includes(options.template)) {
      // Use framework-specific vite config
      const viteConfigTemplate = readFileSync(
        join(__dirname, '..', 'templates', options.template, 'vite.config.js.template'),
        'utf-8'
      );
      writeFileSync(join(outDir, 'vite.config.js'), viteConfigTemplate, 'utf-8');
    } else {
      // Use vanilla vite config
      const viteConfigSrc = join(__dirname, '..', '..', 'vite.config.js');
      if (existsSync(viteConfigSrc)) {
        cpSync(viteConfigSrc, join(outDir, 'vite.config.js'));
      }
    }
    console.log(chalk.green('✓ Generated vite.config.js'));
    
    // Copy .gitignore
    const gitignoreSrc = join(__dirname, '..', '..', '.gitignore');
    if (existsSync(gitignoreSrc)) {
      cpSync(gitignoreSrc, join(outDir, '.gitignore'));
      console.log(chalk.green('✓ Copied .gitignore'));
    }
    
    // Copy tsconfig.json for Angular
    if (options.template === 'angular') {
      const tsconfigTemplate = readFileSync(
        join(__dirname, '..', 'templates', 'angular', 'tsconfig.json.template'),
        'utf-8'
      );
      writeFileSync(join(outDir, 'tsconfig.json'), tsconfigTemplate, 'utf-8');
      console.log(chalk.green('✓ Generated tsconfig.json'));
    }
    
    // Summary
    console.log(chalk.blue('\n📋 Summary:'));
    console.log(chalk.gray(`  Project: ${packageJson.name}`));
    console.log(chalk.gray(`  Parameters: ${Object.keys(schema.properties || {}).length}`));
    console.log(chalk.gray(`  Template: ${options.template}`));
    console.log(chalk.gray(`  Output: ${outDir}`));
    
    console.log(chalk.green('\n✓ Scaffolding complete!'));
    console.log(chalk.blue('\n🚀 Next steps:'));
    console.log(chalk.gray(`  cd ${options.out}`));
    console.log(chalk.gray('  npm install'));
    console.log(chalk.gray('  npm run dev'));
    
  } catch (err) {
    console.error(chalk.red(`✗ Unexpected error: ${err.message}`));
    if (process.env.DEBUG) {
      console.error(err.stack);
    }
    process.exit(1);
  }
}
