/**
 * Theme command - Generate custom color themes for web apps
 * @license GPL-3.0-or-later
 */

import { writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import chalk from 'chalk';

/**
 * Theme presets with carefully selected color palettes
 */
const THEME_PRESETS = {
  blue: {
    name: 'Blue (Default)',
    description: 'Professional blue theme with good contrast',
    colors: {
      primary: '#2563eb',
      primaryHover: '#1d4ed8',
      primaryActive: '#1e40af',
      secondary: '#64748b',
      secondaryHover: '#475569',
      background: '#ffffff',
      backgroundAlt: '#f8fafc',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#e2e8f0',
      error: '#dc2626',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#3b82f6',
    },
  },
  purple: {
    name: 'Purple',
    description: 'Creative purple theme for artistic projects',
    colors: {
      primary: '#9333ea',
      primaryHover: '#7e22ce',
      primaryActive: '#6b21a8',
      secondary: '#64748b',
      secondaryHover: '#475569',
      background: '#ffffff',
      backgroundAlt: '#faf5ff',
      surface: '#ffffff',
      surfaceHover: '#f3e8ff',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#e9d5ff',
      error: '#dc2626',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#a855f7',
    },
  },
  green: {
    name: 'Green',
    description: 'Fresh green theme for nature-focused projects',
    colors: {
      primary: '#059669',
      primaryHover: '#047857',
      primaryActive: '#065f46',
      secondary: '#64748b',
      secondaryHover: '#475569',
      background: '#ffffff',
      backgroundAlt: '#f0fdf4',
      surface: '#ffffff',
      surfaceHover: '#dcfce7',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#bbf7d0',
      error: '#dc2626',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#14b8a6',
    },
  },
  orange: {
    name: 'Orange',
    description: 'Energetic orange theme for dynamic projects',
    colors: {
      primary: '#ea580c',
      primaryHover: '#c2410c',
      primaryActive: '#9a3412',
      secondary: '#64748b',
      secondaryHover: '#475569',
      background: '#ffffff',
      backgroundAlt: '#fff7ed',
      surface: '#ffffff',
      surfaceHover: '#ffedd5',
      text: '#1e293b',
      textSecondary: '#64748b',
      border: '#fed7aa',
      error: '#dc2626',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#f97316',
    },
  },
  slate: {
    name: 'Slate (Monochrome)',
    description: 'Minimal monochrome theme for professional look',
    colors: {
      primary: '#334155',
      primaryHover: '#1e293b',
      primaryActive: '#0f172a',
      secondary: '#64748b',
      secondaryHover: '#475569',
      background: '#ffffff',
      backgroundAlt: '#f8fafc',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      text: '#0f172a',
      textSecondary: '#64748b',
      border: '#e2e8f0',
      error: '#dc2626',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#64748b',
    },
  },
  dark: {
    name: 'Dark Mode',
    description: 'Dark theme for low-light environments',
    colors: {
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      primaryActive: '#1d4ed8',
      secondary: '#94a3b8',
      secondaryHover: '#cbd5e1',
      background: '#0f172a',
      backgroundAlt: '#1e293b',
      surface: '#1e293b',
      surfaceHover: '#334155',
      text: '#f8fafc',
      textSecondary: '#94a3b8',
      border: '#334155',
      error: '#ef4444',
      warning: '#f59e0b',
      success: '#10b981',
      info: '#3b82f6',
    },
  },
};

/**
 * Validate hex color format
 * @param {string} color - Hex color code
 * @returns {boolean} True if valid
 */
function isValidHexColor(color) {
  return /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/.test(color);
}

/**
 * Generate CSS variables from color scheme
 * @param {Object} colors - Color scheme object
 * @param {string} themeName - Theme name for comments
 * @returns {string} CSS content
 */
function generateThemeCSS(colors, themeName = 'Custom') {
  return `/**
 * ${themeName} Theme
 * Generated by OpenSCAD Forge theme command
 * @license GPL-3.0-or-later
 */

:root {
  /* Primary Colors */
  --color-primary: ${colors.primary};
  --color-primary-hover: ${colors.primaryHover};
  --color-primary-active: ${colors.primaryActive};
  
  /* Secondary Colors */
  --color-secondary: ${colors.secondary};
  --color-secondary-hover: ${colors.secondaryHover};
  
  /* Background Colors */
  --color-background: ${colors.background};
  --color-background-alt: ${colors.backgroundAlt};
  --color-surface: ${colors.surface};
  --color-surface-hover: ${colors.surfaceHover};
  
  /* Text Colors */
  --color-text: ${colors.text};
  --color-text-secondary: ${colors.textSecondary};
  
  /* Border Colors */
  --color-border: ${colors.border};
  
  /* Status Colors */
  --color-error: ${colors.error};
  --color-warning: ${colors.warning};
  --color-success: ${colors.success};
  --color-info: ${colors.info};
  
  /* Shadows */
  --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
  --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
  
  /* Transitions */
  --transition-fast: 150ms ease-in-out;
  --transition-base: 250ms ease-in-out;
  --transition-slow: 350ms ease-in-out;
}

/* Apply theme colors to common elements */
body {
  background-color: var(--color-background);
  color: var(--color-text);
}

.btn-primary,
button.primary {
  background-color: var(--color-primary);
  color: white;
}

.btn-primary:hover,
button.primary:hover {
  background-color: var(--color-primary-hover);
}

.btn-primary:active,
button.primary:active {
  background-color: var(--color-primary-active);
}

.btn-secondary,
button.secondary {
  background-color: var(--color-secondary);
  color: white;
}

.btn-secondary:hover,
button.secondary:hover {
  background-color: var(--color-secondary-hover);
}

.surface,
.panel,
.card {
  background-color: var(--color-surface);
  border: 1px solid var(--color-border);
}

.surface:hover,
.panel:hover,
.card:hover {
  background-color: var(--color-surface-hover);
}

.text-secondary {
  color: var(--color-text-secondary);
}

.error,
.alert-error {
  color: var(--color-error);
}

.warning,
.alert-warning {
  color: var(--color-warning);
}

.success,
.alert-success {
  color: var(--color-success);
}

.info,
.alert-info {
  color: var(--color-info);
}

/* High contrast mode support */
@media (prefers-contrast: high) {
  :root {
    --color-border: ${colors.text};
  }
}

/* Reduced motion support */
@media (prefers-reduced-motion: reduce) {
  :root {
    --transition-fast: 0s;
    --transition-base: 0s;
    --transition-slow: 0s;
  }
}
`;
}

/**
 * Generate lighter/darker shade of a color
 * @param {string} hex - Hex color code
 * @param {number} amount - Amount to lighten (positive) or darken (negative)
 * @returns {string} New hex color
 */
function shadeColor(hex, amount) {
  // Remove # if present
  hex = hex.replace('#', '');
  
  // Convert to RGB
  let r = parseInt(hex.substring(0, 2), 16);
  let g = parseInt(hex.substring(2, 4), 16);
  let b = parseInt(hex.substring(4, 6), 16);
  
  // Calculate new values
  r = Math.max(0, Math.min(255, r + amount));
  g = Math.max(0, Math.min(255, g + amount));
  b = Math.max(0, Math.min(255, b + amount));
  
  // Convert back to hex
  return '#' + ((1 << 24) | (r << 16) | (g << 8) | b).toString(16).slice(1);
}

/**
 * Create custom theme from user-provided colors
 * @param {Object} options - User color options
 * @returns {Object} Complete color scheme
 */
function createCustomTheme(options) {
  const primary = options.primary || '#2563eb';
  const secondary = options.secondary || '#64748b';
  const background = options.background || '#ffffff';
  
  // Auto-generate related colors
  return {
    primary,
    primaryHover: shadeColor(primary, -20),
    primaryActive: shadeColor(primary, -40),
    secondary,
    secondaryHover: shadeColor(secondary, -20),
    background,
    backgroundAlt: shadeColor(background, -5),
    surface: background,
    surfaceHover: shadeColor(background, -10),
    text: background === '#ffffff' ? '#1e293b' : '#f8fafc',
    textSecondary: background === '#ffffff' ? '#64748b' : '#94a3b8',
    border: background === '#ffffff' ? '#e2e8f0' : '#334155',
    error: '#dc2626',
    warning: '#f59e0b',
    success: '#10b981',
    info: primary,
  };
}

/**
 * Theme command handler
 * @param {Object} options - Command options
 */
export async function themeCommand(options) {
  try {
    console.log(chalk.blue('🎨 OpenSCAD Forge - Theme Generator'));
    
    // List presets if requested
    if (options.list) {
      console.log(chalk.blue('\n📋 Available Theme Presets:\n'));
      for (const [key, preset] of Object.entries(THEME_PRESETS)) {
        console.log(chalk.bold(key));
        console.log(chalk.gray(`  ${preset.description}`));
        console.log(chalk.gray(`  Primary: ${preset.colors.primary}`));
        console.log();
      }
      return;
    }
    
    // Determine output path
    const outPath = options.out || './theme.css';
    const resolvedPath = resolve(outPath);
    
    // Check if file exists
    if (existsSync(resolvedPath) && !options.force) {
      console.error(chalk.red(`✗ File already exists: ${resolvedPath}`));
      console.log(chalk.yellow('Use --force to overwrite'));
      process.exit(1);
    }
    
    let colors;
    let themeName;
    
    // Generate theme based on options
    if (options.custom) {
      // Custom theme from user colors
      if (!options.primary && !options.secondary && !options.background) {
        console.error(chalk.red('✗ Custom theme requires at least one color'));
        console.log(chalk.yellow('Use --primary, --secondary, or --background'));
        process.exit(1);
      }
      
      // Validate hex colors
      if (options.primary && !isValidHexColor(options.primary)) {
        console.error(chalk.red(`✗ Invalid primary color: ${options.primary}`));
        process.exit(1);
      }
      if (options.secondary && !isValidHexColor(options.secondary)) {
        console.error(chalk.red(`✗ Invalid secondary color: ${options.secondary}`));
        process.exit(1);
      }
      if (options.background && !isValidHexColor(options.background)) {
        console.error(chalk.red(`✗ Invalid background color: ${options.background}`));
        process.exit(1);
      }
      
      colors = createCustomTheme({
        primary: options.primary,
        secondary: options.secondary,
        background: options.background,
      });
      themeName = 'Custom';
      console.log(chalk.green('✓ Generated custom theme'));
    } else if (options.preset) {
      // Use preset theme
      const preset = THEME_PRESETS[options.preset];
      if (!preset) {
        console.error(chalk.red(`✗ Unknown preset: ${options.preset}`));
        console.log(chalk.yellow('Use --list to see available presets'));
        process.exit(1);
      }
      
      colors = preset.colors;
      themeName = preset.name;
      console.log(chalk.green(`✓ Using preset: ${themeName}`));
    } else {
      // Default to blue theme
      colors = THEME_PRESETS.blue.colors;
      themeName = THEME_PRESETS.blue.name;
      console.log(chalk.green(`✓ Using default theme: ${themeName}`));
    }
    
    // Generate CSS
    const css = generateThemeCSS(colors, themeName);
    
    // Write file
    writeFileSync(resolvedPath, css, 'utf-8');
    console.log(chalk.green(`✓ Theme saved to: ${resolvedPath}`));
    
    // Usage instructions
    console.log(chalk.blue('\n📋 Next Steps:'));
    console.log(chalk.gray('1. Copy the theme file to your web app:'));
    console.log(chalk.gray(`   cp ${outPath} <webapp>/src/styles/theme.css`));
    console.log(chalk.gray('2. Import it in your main CSS or HTML:'));
    console.log(chalk.gray('   @import "./theme.css";'));
    console.log(chalk.gray('3. (Optional) Customize colors in the :root selector'));
    
    // Preview colors
    console.log(chalk.blue('\n🎨 Color Preview:'));
    console.log(chalk.gray(`  Primary: ${colors.primary}`));
    console.log(chalk.gray(`  Secondary: ${colors.secondary}`));
    console.log(chalk.gray(`  Background: ${colors.background}`));
    console.log(chalk.gray(`  Text: ${colors.text}`));
    
  } catch (err) {
    console.error(chalk.red(`✗ Unexpected error: ${err.message}`));
    if (process.env.DEBUG) {
      console.error(err.stack);
    }
    process.exit(1);
  }
}
